/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Robots = {
  noIndex?: boolean;
  noFollow?: boolean;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Icon = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type SupportUsSection = {
  _type: "supportUsSection";
  heading?: string;
  subheading?: string;
  cta?: Link;
  image?: Img;
};

export type PodcastSection = {
  _type: "podcastSection";
  heading?: string;
  subheading?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type PeopleSection = {
  _type: "peopleSection";
  heading?: string;
  people?: Array<{
    groupName?: string;
    members?: Array<
      {
        _key: string;
      } & AuthorReference
    >;
    _type: "group";
    _key: string;
  }>;
};

export type NewPublicationsSection = {
  _type: "newPublicationsSection";
  heading?: string;
};

export type JoinUsSection = {
  _type: "joinUsSection";
  heading?: string;
  subheading?: string;
  benefits?: Array<{
    title?: string;
    description?: string;
    icon?: Icon;
    link?: Link;
    _type: "benefit";
    _key: string;
  }>;
};

export type HeroSection = {
  _type: "heroSection";
  heading?: string;
  subheading?: string;
  backgroundImage?: Img;
  cta?: Link;
  secondaryCta?: Link;
};

export type EventsSection = {
  _type: "eventsSection";
  heading?: string;
};

export type DivisionsSection = {
  _type: "divisionsSection";
  heading?: string;
  subheading?: string;
};

export type AboutUsSection = {
  _type: "aboutUsSection";
  heading?: string;
  image?: Img;
  content?: Array<{
    text?: string;
    icon?: Img;
    _type: "column";
    _key: string;
  }>;
};

export type PageBuilder = Array<
  | ({
      _key: string;
    } & AboutUsSection)
  | ({
      _key: string;
    } & DivisionsSection)
  | ({
      _key: string;
    } & EventsSection)
  | ({
      _key: string;
    } & HeroSection)
  | ({
      _key: string;
    } & JoinUsSection)
  | ({
      _key: string;
    } & NewPublicationsSection)
  | ({
      _key: string;
    } & PeopleSection)
  | ({
      _key: string;
    } & PodcastSection)
  | ({
      _key: string;
    } & SupportUsSection)
>;

export type LinkButton = {
  _type: "linkButton";
  variant?: "primary" | "secondary" | "text" | "link";
  link?: Link;
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type EventReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "event";
};

export type DivisionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "division";
};

export type Link = {
  _type: "link";
  linkType?: "page" | "post" | "event" | "division" | "href";
  text?: string;
  href?: string;
  page?: PageReference;
  homepage?: boolean;
  post?: PostReference;
  event?: EventReference;
  division?: DivisionReference;
  openInNewTab?: boolean;
};

export type PostsSection = {
  _type: "postsSection";
  displayNumber?: number;
};

export type LeadSection = {
  _type: "leadSection";
  title?: string;
  subtitle?: string;
};

export type Img = {
  _type: "img";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
};

export type RichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  canonical?: string;
  ogImage?: Img;
  twitterCreator?: string;
  robots?: Robots;
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  seo?: Seo;
  documentName?: string;
  sections?: Array<
    | ({
        _key: string;
      } & Img)
    | ({
        _key: string;
      } & LeadSection)
    | ({
        _key: string;
      } & PostsSection)
  >;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  icon?: IconPicker;
};

export type IconPicker = {
  _type: "iconPicker";
  provider?: string;
  name?: string;
  svg?: string;
};

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReference = Array<
  {
    _key: string;
  } & InternationalizedArrayReferenceValue
>;

export type NavigationReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "navigation";
};

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?:
    | PageReference
    | PostReference
    | EventReference
    | DivisionReference
    | AuthorReference
    | NavigationReference;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  button?: Array<
    {
      _key: string;
    } & LinkButton
  >;
  links?: Array<
    | {
        name?: string;
        header?: string;
        description?: string;
        columns?: Array<{
          header?: string;
          items?: Array<
            {
              _key: string;
            } & Link
          >;
          _key: string;
        }>;
        _type: "dropdown";
        _key: string;
      }
    | ({
        _key: string;
      } & Link)
  >;
  locale?: string;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  seo?: Seo;
  name?: string;
  slug?: Slug;
  startDate?: string;
  endDate?: string;
  division?: DivisionReference;
  venue?: string;
  address?: string;
  excerpt?: string;
  description?: RichText;
  image?: Img;
  registrationUrl?: string;
};

export type Division = {
  _id: string;
  _type: "division";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  seo?: Seo;
  name?: string;
  slug?: Slug;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  seo?: Seo;
  title?: string;
  slug?: Slug;
  author?: AuthorReference;
  image?: Img;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  publishedAt?: string;
  body?: RichText;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  name?: string;
  slug?: Slug;
  img?: Img;
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  heading?: string;
  subheading?: string;
  pageBuilder?: PageBuilder;
  locale?: string;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Robots
  | SanityImageAssetReference
  | Icon
  | SupportUsSection
  | PodcastSection
  | AuthorReference
  | PeopleSection
  | NewPublicationsSection
  | JoinUsSection
  | HeroSection
  | EventsSection
  | DivisionsSection
  | AboutUsSection
  | PageBuilder
  | LinkButton
  | PageReference
  | PostReference
  | EventReference
  | DivisionReference
  | Link
  | PostsSection
  | LeadSection
  | Img
  | RichText
  | Seo
  | Home
  | Settings
  | Category
  | IconPicker
  | TranslationMetadata
  | InternationalizedArrayReference
  | NavigationReference
  | InternationalizedArrayReferenceValue
  | Navigation
  | Event
  | Division
  | Slug
  | CategoryReference
  | Post
  | Author
  | Page
  | SanityImageCrop
  | SanityImageHotspot
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../web/sanity/queries/groq.example.ts
// Variable: postsQuery
// Query: *[_type == "post"] | order(_createdAt desc) {    _id,    _createdAt,    title,    "slug": slug.current,    "author": author->name,    "image": mainImage.asset->url,    description,    "categories": categories[]->title,    body  }
export type PostsQueryResult = Array<{
  _id: string;
  _createdAt: string;
  title: string | null;
  slug: string | null;
  author: string | null;
  image: null;
  description: null;
  categories: Array<string | null> | null;
  body: RichText | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "post"] | order(_createdAt desc) {\n    _id,\n    _createdAt,\n    title,\n    "slug": slug.current,\n    "author": author->name,\n    "image": mainImage.asset->url,\n    description,\n    "categories": categories[]->title,\n    body\n  }\n': PostsQueryResult;
  }
}
