/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Robots = {
  noIndex?: boolean;
  noFollow?: boolean;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type FileDataFile = {
  asset?: SanityFileAssetReference;
  media?: unknown; // Unable to locate the referenced type "media" in schema
  _type: "file";
};

export type DocumentsSection = {
  _type: "documentsSection";
  groups?: Array<{
    title?: string;
    items?: Array<
      | {
          file?: FileDataFile;
          title?: string;
          date?: string;
          _type: "fileData";
          _key: string;
        }
      | {
          title?: string;
          items?: Array<{
            file?: FileDataFile;
            title?: string;
            date?: string;
            _type: "fileData";
            _key: string;
          }>;
          _type: "documentSubgroup";
          _key: string;
        }
    >;
    _type: "documentGroup";
    _key: string;
  }>;
};

export type EventsListSection = {
  _type: "eventsListSection";
  dummy?: string;
};

export type ExpertsListSection = {
  _type: "expertsListSection";
  dummy?: string;
};

export type HeadingSection = {
  _type: "headingSection";
  heading?: string;
  subheading?: string;
  image?: Img;
};

export type DivisionsListSection = {
  _type: "divisionsListSection";
  header?: string;
  text?: string;
};

export type EventsDivisionsSection = {
  _type: "eventsDivisionsSection";
  header?: string;
};

export type JoinUsDivisionsSection = {
  _type: "joinUsDivisionsSection";
  header?: string;
  features?: Array<{
    icon?: Img;
    header?: string;
    description?: string;
    _key: string;
  }>;
  button?: Link;
};

export type WhatWeDoDivisionsSection = {
  _type: "whatWeDoDivisionsSection";
  title?: string;
  whatWeDo?: Array<string>;
};

export type PersonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "person";
};

export type TeamDivisionsSection = {
  _type: "teamDivisionsSection";
  header?: string;
  text?: string;
  members?: Array<
    {
      _key: string;
    } & PersonReference
  >;
};

export type UniversalHeroSection = {
  _type: "universalHeroSection";
  header?: string;
  description?: string;
  image?: Img;
};

export type ContactSection = {
  _type: "contactSection";
  heading?: string;
  subtitle?: string;
  contactEmail?: string;
  contactAddress?: string;
  recipientEmail?: string;
};

export type SupportUsSection = {
  _type: "supportUsSection";
  heading?: string;
  subheading?: string;
  description?: string;
  cta?: Link;
  image?: Img;
};

export type PodcastSection = {
  _type: "podcastSection";
  heading?: string;
  subheading?: string;
  embed?: string;
  link?: Link;
};

export type PeopleSection = {
  _type: "peopleSection";
  heading?: string;
  people?: Array<{
    groupName?: string;
    members?: Array<
      {
        _key: string;
      } & PersonReference
    >;
    _type: "group";
    _key: string;
  }>;
};

export type NewPublicationsSection = {
  _type: "newPublicationsSection";
  heading?: string;
};

export type JoinUsSection = {
  _type: "joinUsSection";
  heading?: string;
  subheading?: string;
  benefits?: Array<{
    title?: string;
    description?: string;
    icon?: Img;
    link?: Link;
    _type: "benefit";
    _key: string;
  }>;
};

export type HeroSection = {
  _type: "heroSection";
  heading?: string;
  subheading?: string;
  backgroundImage?: Img;
  cta?: Link;
  secondaryCta?: Link;
};

export type EventsSection = {
  _type: "eventsSection";
  heading?: string;
  link?: Link;
};

export type DivisionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "division";
};

export type DivisionsSection = {
  _type: "divisionsSection";
  heading?: string;
  subheading?: string;
  description?: string;
  divisions?: Array<
    {
      _key: string;
    } & DivisionReference
  >;
};

export type AboutUsSection = {
  _type: "aboutUsSection";
  heading?: string;
  image?: Img;
  content?: Array<{
    text?: string;
    icon?: Img;
    _type: "column";
    _key: string;
  }>;
};

export type Socials = Array<{
  platform?:
    | "facebook"
    | "instagram"
    | "linkedin"
    | "twitter"
    | "youtube"
    | "spotify";
  url?: string;
  _type: "socialLink";
  _key: string;
}>;

export type PageBuilder = Array<
  | ({
      _key: string;
    } & AboutUsSection)
  | ({
      _key: string;
    } & DivisionsSection)
  | ({
      _key: string;
    } & EventsSection)
  | ({
      _key: string;
    } & HeadingSection)
  | ({
      _key: string;
    } & HeroSection)
  | ({
      _key: string;
    } & JoinUsSection)
  | ({
      _key: string;
    } & NewPublicationsSection)
  | ({
      _key: string;
    } & PeopleSection)
  | ({
      _key: string;
    } & PodcastSection)
  | ({
      _key: string;
    } & SupportUsSection)
  | ({
      _key: string;
    } & ContactSection)
  | ({
      _key: string;
    } & UniversalHeroSection)
  | ({
      _key: string;
    } & TeamDivisionsSection)
  | ({
      _key: string;
    } & WhatWeDoDivisionsSection)
  | ({
      _key: string;
    } & JoinUsDivisionsSection)
  | ({
      _key: string;
    } & EventsDivisionsSection)
  | ({
      _key: string;
    } & DivisionsListSection)
  | ({
      _key: string;
    } & ExpertsListSection)
  | ({
      _key: string;
    } & EventsListSection)
  | ({
      _key: string;
    } & DocumentsSection)
>;

export type LinkButton = {
  _type: "linkButton";
  variant?: "primary" | "secondary" | "text" | "link";
  link?: Link;
};

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type PublicationReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "publication";
};

export type Link = {
  _type: "link";
  linkType?: "page" | "publication" | "division" | "href";
  text?: string;
  href?: string;
  page?: PageReference;
  homepage?: boolean;
  division?: DivisionReference;
  publication?: PublicationReference;
  openInNewTab?: boolean;
  isExternal?: boolean;
};

export type PostsSection = {
  _type: "postsSection";
  displayNumber?: number;
};

export type LeadSection = {
  _type: "leadSection";
  title?: string;
  subtitle?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Img = {
  _type: "img";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
};

export type RichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  canonical?: string;
  ogImage?: Img;
  twitterCreator?: string;
  robots?: Robots;
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  seo?: Seo;
  documentName?: string;
  sections?: Array<
    | ({
        _key: string;
      } & Img)
    | ({
        _key: string;
      } & LeadSection)
    | ({
        _key: string;
      } & PostsSection)
  >;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  icon?: IconPicker;
};

export type IconPicker = {
  _type: "iconPicker";
  provider?: string;
  name?: string;
  svg?: string;
};

export type PersonGroups = {
  _id: string;
  _type: "personGroups";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  groups?: Array<{
    name?: InternationalizedArrayString;
    slug?: Slug;
    subgroups?: Array<{
      name?: InternationalizedArrayString;
      slug?: Slug;
      _type: "subgroup";
      _key: string;
    }>;
    _type: "group";
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type InternationalizedArrayString = Array<
  {
    _key: string;
  } & InternationalizedArrayStringValue
>;

export type InternationalizedArrayTextValue = {
  _type: "internationalizedArrayTextValue";
  value?: string;
  language?: string;
};

export type InternationalizedArrayStringValue = {
  _type: "internationalizedArrayStringValue";
  value?: string;
  language?: string;
};

export type InternationalizedArrayText = Array<
  {
    _key: string;
  } & InternationalizedArrayTextValue
>;

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReference = Array<
  {
    _key: string;
  } & InternationalizedArrayReferenceValue
>;

export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type EventReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "event";
};

export type NavigationReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "navigation";
};

export type TagReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag";
};

export type TagCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tagCategory";
};

export type FooterReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "footer";
};

export type TranslationsReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "translations";
};

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?:
    | PageReference
    | PostReference
    | EventReference
    | DivisionReference
    | NavigationReference
    | PublicationReference
    | TagReference
    | TagCategoryReference
    | FooterReference
    | TranslationsReference;
  language?: string;
};

export type Translations = {
  _id: string;
  _type: "translations";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  global?: {
    results?: string;
    search?: string;
  };
  navigation?: {
    home?: string;
    skipToContent?: string;
    aboutUs?: string;
    experts?: string;
  };
  buttons?: {
    support?: string;
  };
  events?: {
    upcoming?: string;
    archive?: string;
    signUp?: string;
    noEvents?: string;
  };
  people?: {
    seeAll?: string;
    groupName?: string;
    allGroups?: string;
  };
  contactForm?: {
    starsign?: string;
    firstName?: string;
    lastName?: string;
    email?: string;
    phone?: string;
    subject?: string;
    message?: string;
    submit?: string;
    sending?: string;
    requiredError?: string;
    placeholders?: {
      firstName?: string;
      lastName?: string;
      email?: string;
      phone?: string;
      subject?: string;
      message?: string;
    };
  };
  divisions?: {
    divisionNotFound?: string;
  };
  locale?: string;
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  email?: string;
  phone?: string;
  socials?: Socials;
  address?: string;
  identfiers?: string;
  nav?: Array<
    {
      _key: string;
    } & Link
  >;
  copyright?: string;
  links?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type Tag = {
  _id: string;
  _type: "tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  seo?: Seo;
  name?: string;
  slug?: Slug;
  category?: TagCategoryReference;
};

export type TagCategory = {
  _id: string;
  _type: "tagCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
  locale?: string;
  title?: string;
  description?: string;
};

export type Publication = {
  _id: string;
  _type: "publication";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  seo?: Seo;
  type?: "article" | "news" | "guide" | "review";
  title?: string;
  excerpt?: string;
  slug?: Slug;
  date?: string;
  mainImage?: Img;
  author?: PersonReference;
  pdfFile?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  text?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
  >;
  tags?: Array<
    {
      _key: string;
    } & TagReference
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  button?: Array<
    {
      _key: string;
    } & LinkButton
  >;
  links?: Array<
    | {
        name?: string;
        header?: string;
        description?: string;
        columns?: Array<{
          header?: string;
          items?: Array<
            {
              _key: string;
            } & Link
          >;
          _key: string;
        }>;
        _type: "dropdown";
        _key: string;
      }
    | ({
        _key: string;
      } & Link)
  >;
  locale?: string;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  seo?: Seo;
  name?: string;
  type?: string;
  startDate?: string;
  endDate?: string;
  isOnline?: boolean;
  division?: DivisionReference;
  venue?: string;
  address?: string;
  excerpt?: string;
  registrationUrl?: string;
};

export type Division = {
  _id: string;
  _type: "division";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  seo?: Seo;
  name?: string;
  slug?: Slug;
  coverImage?: Img;
  pageBuilder?: Array<
    | ({
        _key: string;
      } & UniversalHeroSection)
    | ({
        _key: string;
      } & WhatWeDoDivisionsSection)
    | ({
        _key: string;
      } & JoinUsDivisionsSection)
    | ({
        _key: string;
      } & TeamDivisionsSection)
    | ({
        _key: string;
      } & EventsDivisionsSection)
  >;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  seo?: Seo;
  title?: string;
  slug?: Slug;
  author?: PersonReference;
  image?: Img;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  publishedAt?: string;
  body?: RichText;
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  locale?: string;
  name?: string;
  group?: string;
  img?: Img;
  title?: InternationalizedArrayString;
  bio?: InternationalizedArrayText;
  socials?: Socials;
  order?: number;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  pageBuilder?: PageBuilder;
  locale?: string;
  seo?: Seo;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Robots
  | SanityFileAssetReference
  | FileDataFile
  | DocumentsSection
  | EventsListSection
  | ExpertsListSection
  | HeadingSection
  | DivisionsListSection
  | EventsDivisionsSection
  | JoinUsDivisionsSection
  | WhatWeDoDivisionsSection
  | PersonReference
  | TeamDivisionsSection
  | UniversalHeroSection
  | ContactSection
  | SupportUsSection
  | PodcastSection
  | PeopleSection
  | NewPublicationsSection
  | JoinUsSection
  | HeroSection
  | EventsSection
  | DivisionReference
  | DivisionsSection
  | AboutUsSection
  | Socials
  | PageBuilder
  | LinkButton
  | PageReference
  | PublicationReference
  | Link
  | PostsSection
  | LeadSection
  | SanityImageAssetReference
  | Img
  | RichText
  | Seo
  | Home
  | Settings
  | Category
  | IconPicker
  | PersonGroups
  | Slug
  | InternationalizedArrayString
  | InternationalizedArrayTextValue
  | InternationalizedArrayStringValue
  | InternationalizedArrayText
  | TranslationMetadata
  | InternationalizedArrayReference
  | PostReference
  | EventReference
  | NavigationReference
  | TagReference
  | TagCategoryReference
  | FooterReference
  | TranslationsReference
  | InternationalizedArrayReferenceValue
  | Translations
  | Footer
  | Tag
  | TagCategory
  | Publication
  | SanityImageCrop
  | SanityImageHotspot
  | Navigation
  | Event
  | Division
  | CategoryReference
  | Post
  | Person
  | Page
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;
